sudo: required
services:
  - docker

#build a test version of our client project, we user development docker file, coz prod docker file doesn't allow to run tests
# -f to override the default docker file
before_install:
  - docker build -t addi7568/react-test -f ./client/Dockerfile.dev ./client

#-- -- coverage to make the test exit with a status code and not go into watch mode
script:
  - docker run -e CI=true aadi7568/react-test npm test -- --coverage

after_success:
  - docker build -t aadi7568/multi-client ./client
  - docker build -t aadi7568/multi-nginx ./nginx
  - docker build -t aadi7568/multi-server ./server
  - docker build -t aadi7568/multi-worker ./worker

  #log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take all images and push to docker hub
  - docker push aadi7568/multi-client
  - docker push aadi7568/multi-nginx
  - docker push aadi7568/multi-server
  - docker push aadi7568/multi-worker